[package]
name = "coffee_maker_driver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "coffee_maker_driver"
path = "src/main.rs"

[dependencies]
rclrs = "*"
obd_coffee_maker_interface = "*"
std_msgs = "*"
anyhow = "1"
rumqttc = "0.12.0"
tokio = { version = "1.0", features = ["full"] }